### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [lucasxlu/XCloud#1]
Hello @lucasxlu 

I would like to contribute to xcloud if you let me. I have a very good logo idea and I even designed a logo. If you like it, I can send you all the files via a pr. 

I will wait for feedback. Have a nice day!

![xcloud](https://user-images.githubusercontent.com/36298335/46571616-81a31b00-c9d4-11e8-8cac-443f636850a2.jpg)

**Comment by lucasxlu** [comment]
> Hello @lucasxlu
> 
> I would like to contribute to xcloud if you let me. I have a very good logo idea and I even designed a logo. If you like it, I can send you all the files via a pr.
> 
> I will wait for feedback. Have a nice day!
> 
> ![xcloud](https://user-images.githubusercontent.com/36298335/46571616-81a31b00-c9d4-11e8-8cac-443f636850a2.jpg)

THX for your attention about my project and your logo contribution. I find the logo quite beautiful. Your design can be used for the logo of this project if you don't mind. :-D

**Comment by reallinfo** [comment]
Of course! I would be very happy. I'll send you all the files as soon as possible.

**Comment by reallinfo** [comment]
which variation do you prefer? Bold x or thin X? Also, Are you satisfied with the colors?

![xcloud2](https://user-images.githubusercontent.com/36298335/46572214-558c9780-c9de-11e8-83d6-25573c517320.jpg)

**Comment by lucasxlu** [comment]
> which variation do you prefer? Bold x or thin X? Also, Are you satisfied with the colors?

Well, I prefer the upper one with __bold style__. I think the color very bright and lively, which is quite suitable for technology projects. Thanks again for your design. 😄

**Comment by reallinfo** [comment]
you're welcome. I sent a pr.

If you need anything about the design, you can contact me.
